backend:
  image: shreybatra/sample-backend
  port: 8000
  redisUri: "redis://redis-svc:6379"

frontend:
  image: shreybatra/sample-frontend
  port: 5175
  nodePort: 31000
  backendUrl: "http://backend-svc:8000"

redis:
  image: redis
  port: 6379 
